items:
  clan-information:
    icon: PLAYER_HEAD
    display-name: "Clan %clan%"
    lore:
      - ""
      - "test"
  clan-information-full:
    icon: PLAYER_HEAD
    display-name: "Clan %clan%"
    lore:
      - ""
      - "test"